/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: AddWasmModuleCommandRequest.proto */

#ifndef PROTOBUF_C_AddWasmModuleCommandRequest_2eproto__INCLUDED
#define PROTOBUF_C_AddWasmModuleCommandRequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "Object_AddWasmModule_Request.pb-c.h"

typedef struct _DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest;


/* --- enums --- */


/* --- messages --- */

struct  _DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest
{
  ProtobufCMessage base;
  DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *wasmmodule;
};
#define DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__ADD_WASM_MODULE_COMMAND_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__descriptor) \
    , NULL }


/* DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest methods */
void   dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__init
                     (DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest         *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest   *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__pack
                     (const DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest   *message,
                      uint8_t             *out);
size_t dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest   *message,
                      ProtobufCBuffer     *buffer);
DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest *
       dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest_Closure)
                 (const DtmiProtobufTestTinykubePrototype1__AddWasmModuleCommandRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__add_wasm_module_command_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_AddWasmModuleCommandRequest_2eproto__INCLUDED */
