/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Array_AddWasmModule_Request_WasmModuleContent.proto */

#ifndef PROTOBUF_C_Array_5fAddWasmModule_5fRequest_5fWasmModuleContent_2eproto__INCLUDED
#define PROTOBUF_C_Array_5fAddWasmModule_5fRequest_5fWasmModuleContent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent;


/* --- enums --- */


/* --- messages --- */

struct  _DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent
{
  ProtobufCMessage base;
  size_t n_value;
  int32_t *value;
};
#define DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__ARRAY__ADD_WASM_MODULE__REQUEST__WASM_MODULE_CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor) \
    , 0,NULL }


/* DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent methods */
void   dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__init
                     (DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent         *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent   *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__pack
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent   *message,
                      uint8_t             *out);
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent   *message,
                      ProtobufCBuffer     *buffer);
DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *
       dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent_Closure)
                 (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Array_5fAddWasmModule_5fRequest_5fWasmModuleContent_2eproto__INCLUDED */
