/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Array_AddWasmModule_Request_WasmModuleContent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Array_AddWasmModule_Request_WasmModuleContent.pb-c.h"
void   dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__init
                     (DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent         *message)
{
  static const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent init_value = DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__ARRAY__ADD_WASM_MODULE__REQUEST__WASM_MODULE_CONTENT__INIT;
  *message = init_value;
}
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__pack
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *
       dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *)
     protobuf_c_message_unpack (&dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor,
                                allocator, len, data);
}
void   dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__field_descriptors[1] =
{
  {
    "Value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent, n_value),
    offsetof(DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent, value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__field_indices_by_name[] = {
  0,   /* field[0] = Value */
};
static const ProtobufCIntRange dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dtmi_protobufTest_TinykubePrototype__1.Array_AddWasmModule_Request_WasmModuleContent",
  "ArrayAddWasmModuleRequestWasmModuleContent",
  "DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent",
  "dtmi_protobufTest_TinykubePrototype__1",
  sizeof(DtmiProtobufTestTinykubePrototype1__ArrayAddWasmModuleRequestWasmModuleContent),
  1,
  dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__field_descriptors,
  dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__field_indices_by_name,
  1,  dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__number_ranges,
  (ProtobufCMessageInit) dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
