/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CreateWamrRuntimeCommandResponse.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CreateWamrRuntimeCommandResponse.pb-c.h"
void   dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__init
                     (DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse         *message)
{
  static const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse init_value = DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__CREATE_WAMR_RUNTIME_COMMAND_RESPONSE__INIT;
  *message = init_value;
}
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *message)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__pack
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *
       dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *)
     protobuf_c_message_unpack (&dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor,
                                allocator, len, data);
}
void   dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse, has_result),
    offsetof(DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dtmi_protobufTest_TinykubePrototype__1.CreateWamrRuntimeCommandResponse",
  "CreateWamrRuntimeCommandResponse",
  "DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse",
  "dtmi_protobufTest_TinykubePrototype__1",
  sizeof(DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandResponse),
  1,
  dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__field_descriptors,
  dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__field_indices_by_name,
  1,  dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__number_ranges,
  (ProtobufCMessageInit) dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
