/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CreateWamrRuntimeCommandRequest.proto */

#ifndef PROTOBUF_C_CreateWamrRuntimeCommandRequest_2eproto__INCLUDED
#define PROTOBUF_C_CreateWamrRuntimeCommandRequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest;


/* --- enums --- */


/* --- messages --- */

struct  _DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_heapsize;
  int32_t heapsize;
};
#define DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__CREATE_WAMR_RUNTIME_COMMAND_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__descriptor) \
    , 0, 0 }


/* DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest methods */
void   dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__init
                     (DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest         *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest   *message);
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__pack
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest   *message,
                      uint8_t             *out);
size_t dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest   *message,
                      ProtobufCBuffer     *buffer);
DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest *
       dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest_Closure)
                 (const DtmiProtobufTestTinykubePrototype1__CreateWamrRuntimeCommandRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__create_wamr_runtime_command_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_CreateWamrRuntimeCommandRequest_2eproto__INCLUDED */
