/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Object_AddWasmModule_Request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Object_AddWasmModule_Request.pb-c.h"
void   dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__init
                     (DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest         *message)
{
  static const DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest init_value = DTMI_PROTOBUF_TEST__TINYKUBE_PROTOTYPE__1__OBJECT__ADD_WASM_MODULE__REQUEST__INIT;
  *message = init_value;
}
size_t dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__get_packed_size
                     (const DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *message)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__pack
                     (const DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__pack_to_buffer
                     (const DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *
       dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *)
     protobuf_c_message_unpack (&dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor,
                                allocator, len, data);
}
void   dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__free_unpacked
                     (DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__field_descriptors[3] =
{
  {
    "wasmModuleName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest, wasmmodulename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wasmModuleSize",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest, has_wasmmodulesize),
    offsetof(DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest, wasmmodulesize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wasmModuleContent",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest, wasmmodulecontent),
    &dtmi_protobuf_test__tinykube_prototype__1__array__add_wasm_module__request__wasm_module_content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__field_indices_by_name[] = {
  2,   /* field[2] = wasmModuleContent */
  0,   /* field[0] = wasmModuleName */
  1,   /* field[1] = wasmModuleSize */
};
static const ProtobufCIntRange dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dtmi_protobufTest_TinykubePrototype__1.Object_AddWasmModule_Request",
  "ObjectAddWasmModuleRequest",
  "DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest",
  "dtmi_protobufTest_TinykubePrototype__1",
  sizeof(DtmiProtobufTestTinykubePrototype1__ObjectAddWasmModuleRequest),
  3,
  dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__field_descriptors,
  dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__field_indices_by_name,
  1,  dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__number_ranges,
  (ProtobufCMessageInit) dtmi_protobuf_test__tinykube_prototype__1__object__add_wasm_module__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
